---
- name: Configure dev machine
  hosts: all

  pre_tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg:
          - bash-completion
          - git
          - tmux

  roles:
    - role: vim
    - role: avr
