---
- name: Configure dev machine
  hosts: all

  pre_tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        pkg:
          - bash-completion
          - build-essential
          - cmake
          - tmux
          - tree
          - vim

  roles:
    - role: arm64-toolchain
    - role: avr-toolchain
    - role: git
    - role: python
      python_version: 3.12.1

  post_tasks:
    - name: Download dotfile settings
      git:
        repo: "https://github.com/kyungminkim7/dotfiles.git"
        dest: "{{ ansible_env.HOME }}/dotfiles"

    - name: Set .vimrc symlink
      file:
        src: "{{ ansible_env.HOME }}/dotfiles/.vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
        state: link

    - name: Set .tmux.conf symlink
      file:
        src: "{{ ansible_env.HOME }}/dotfiles/.tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        state: link
