---
- name: Install apt packages
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    state: latest
    pkg:
      - git
      - vim

- name: Set git editor
  git_config:
    name: core.editor
    value: vim
    scope: global
